version: '3'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: note
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: note
    ports:
      - "3308:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d